export const English = {
  LoginTitle: "Login With",
  Guest: "Play as Guest",
  FBLabel: "Facebook",
  PlayNowLabel: "PLAY NOW",
  SelectRoomLabel: "SELECT ROOM",
  Labelwatch: "WATCH",
  Labelsetting: "SETTING",
  Labelmail: "MAILBOX",
  Labelrank: "RANKING",
  Labelchat: "CHAT",
  SelectRoomTitle: "PLAYING ROOM LEVELS",
  SelectRoomSubTitle: "Please choose a room to start playing",
  ClassicRoomLabel: "Classic Room",
  PremiumRoomLabel: "Premium Room",
  KingRoomLabel: "King Room",
  Labeltitle_reward: "WELCOME BACK",
  LabelSubTitle_reward: "Attendance daily to receive Rewards",
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
  Labelclaimed: "CLAIMED",
  Labelclaim: "CLAIM",
  Labelx2reward: "X2 REWARD",
  Labelusername: "User name",
  Labelreferral: "Referral",
  Labelstartdate: "Starting date",
  Labelwallet: "Wallet address",
  PLACEHOLDER_LABEL: "Input wallet address here…",
  Labelsave: "SAVE",
  Labelout: "Logout",
  LabelTitle_profile: "MY PROFILE",
  Labelchiprank: "TOTAL CHIP",
  Labelplayer: "PLAYER",
  LabelGEN: "GENERAL",
  LabelPRIVATE: "PRIVATE",
  LabelSUP: "SUPPORT",
  Labelmusic: "Music",
  Labelsound: "Sound effect",
  Labellanguage: "Language",
  Labelenvi: "Switch to Vietnamese",
  Title1: "Only show the profile to my friends",
  Title2: "Allow others to request friends",
  Title3: "Allow others to invite playing",
};

export const Vietnamese = {
  LoginTitle: "Đăng nhập bằng",
  Guest: "Tài khoản khách",
  FBLabel: "ĐỌC SÁCH",
  PlayNowLabel: "CHƠI NGAY",
  SelectRoomLabel: "CHỌN PHÒNG",
  Labelwatch: "XEM",
  Labelsetting: "CÀI ĐẶT",
  Labelmail: "HÒM THƯ",
  Labelrank: "XẾP HẠNG",
  Labelchat: "NHẮN TIN",
  SelectRoomTitle: "CHỌN CẤP ĐỘ",
  SelectRoomSubTitle: "Chọn cấp độ để bắt đầu chơi",
  ClassicRoomLabel: "Cơ bản",
  PremiumRoomLabel: "Trung cấp",
  KingRoomLabel: "Nâng cao",
  Labeltitle_reward: "CHÀO MỪNG TRỞ LẠI",
  LabelSubTitle_reward: "Đăng nhập mỗi ngày để nhận thưởng",
  Monday: "Thứ hai",
  Tuesday: "Thứ ba",
  Wednesday: "Thứ tư",
  Thursday: "Thứ năm",
  Friday: "Thứ sáu",
  Saturday: "Thứ 7",
  Sunday: "Chủ nhật",
  Labelclaimed: "ĐÃ NHẬN",
  Labelclaim: "NHẬN",
  Labelx2reward: "X2 PHỈNH",
  Labelusername: "Tên người dùng",
  Labelreferral: "Mã giới thiệu",
  Labelstartdate: "Ngày bắt đầu",
  Labelwallet: "Địa chỉ ví",
  PLACEHOLDER_LABEL: "Nhập địa chỉ ví tại đây…",
  Labelsave: "LƯU",
  Labelout: "Đăng xuất",
  LabelTitle_profile: "HỒ SƠ",
  Labelchiprank: "SỐ CHIP",
  Labelplayer: "NGƯỜI CHƠI",
  LabelGEN: "CHUNG",
  LabelPRIVATE: "RIÊNG TƯ",
  LabelSUP: "HỖ TRỢ",
  Labelmusic: "Nhạc",
  Labelsound: "Hiệu ứng",
  Labellanguage: "Ngôn ngữ",
  Labelenvi: "Chuyển sang tiếng anh",
  Title1: "Chỉ hiện thông tin cá nhân cho bạn bè của tôi",
  Title2: "Cho phép người khác gửi lời mời kết bạn",
  Title3: "Cho phép người khác mời chơi",
};
